import { describe, expect, it } from 'vitest'
import type { BookRecord } from '@/lib/books/types'
import {
  autoGeneratedCoverRelativePath,
  resolveBookFolderForBook,
  resolveBookFolderFromUnitPath,
  resolvePrimaryUnitPdfPath,
} from '@/lib/books/book-cover-path'

const sampleBook: BookRecord = {
  id: 'journeys-g4',
  title: 'Journeys G4',
  units: [
    {
      id: 'unit-1',
      title: 'Unit 1',
      filePath: 'book-library/journeys-g4/student-book.pdf',
    },
  ],
}

describe('book-cover-path', () => {
  it('resolves book folder from unit file path', () => {
    expect(resolveBookFolderFromUnitPath('book-library/journeys-g4/student-book.pdf')).toBe('journeys-g4')
  })

  it('builds auto cover relative path', () => {
    expect(autoGeneratedCoverRelativePath('journeys-g4')).toBe('book-library/journeys-g4/cover.jpg')
  })

  it('reads primary unit pdf path', () => {
    expect(resolvePrimaryUnitPdfPath(sampleBook)).toBe('book-library/journeys-g4/student-book.pdf')
  })

  it('resolves book folder from first unit', () => {
    expect(resolveBookFolderForBook(sampleBook)).toBe('journeys-g4')
  })
})
