import 'server-only'

import path from 'node:path'
import { access, mkdir, writeFile } from 'node:fs/promises'
import type { BookLibraryPayload, BookRecord } from '@/lib/books/types'
import {
  autoGeneratedCoverRelativePath,
  resolveBookFolderForBook,
  resolvePrimaryUnitPdfPath,
} from '@/lib/books/book-cover-path'
import { getBookLibraryRoot, saveBookLibraryManifest } from '@/lib/books/server'

export interface BookCoverSyncResult {
  payload: BookLibraryPayload
  /** Books that gained a new coverImagePath this run. */
  updatedBookIds: string[]
  /** Covers written from PDF page 1. */
  generatedCount: number
  /** Existing cover.jpg on disk linked into the manifest. */
  linkedCount: number
}

async function fileExists(absPath: string): Promise<boolean> {
  try {
    await access(absPath)
    return true
  } catch {
    return false
  }
}

function resolveAbsPath(relativePath: string, cwd: string): string {
  return path.resolve(cwd, relativePath.replaceAll('\\', '/'))
}

async function resolveExistingCoverPath(
  book: BookRecord,
  libraryRoot: string,
  cwd: string,
): Promise<string | null> {
  const trimmed = book.coverImagePath?.trim()
  if (trimmed) {
    const abs = resolveAbsPath(trimmed, cwd)
    if (await fileExists(abs)) return trimmed
    return null
  }

  const bookFolder = resolveBookFolderForBook(book)
  if (!bookFolder) return null
  const autoPath = autoGeneratedCoverRelativePath(bookFolder)
  const absAuto = path.resolve(libraryRoot, bookFolder, 'cover.jpg')
  if (await fileExists(absAuto)) return autoPath
  return null
}

async function ensureBookCover(
  book: BookRecord,
  libraryRoot: string,
  cwd: string,
): Promise<{ book: BookRecord; generated: boolean; linked: boolean }> {
  const existing = await resolveExistingCoverPath(book, libraryRoot, cwd)
  if (existing) {
    if (book.coverImagePath?.trim() === existing) {
      return { book, generated: false, linked: false }
    }
    return { book: { ...book, coverImagePath: existing }, generated: false, linked: true }
  }

  const unitPdfPath = resolvePrimaryUnitPdfPath(book)
  const bookFolder = resolveBookFolderForBook(book)
  if (!unitPdfPath || !bookFolder) {
    return { book, generated: false, linked: false }
  }

  const absPdf = resolveAbsPath(unitPdfPath, cwd)
  if (!(await fileExists(absPdf))) {
    return { book, generated: false, linked: false }
  }

  const bookDir = path.resolve(libraryRoot, bookFolder)
  const absCover = path.resolve(bookDir, 'cover.jpg')
  if (!absCover.startsWith(bookDir)) {
    return { book, generated: false, linked: false }
  }

  try {
    await mkdir(bookDir, { recursive: true })
    const { renderPdfPageOneToJpegBuffer } = await import('@/lib/books/generate-book-cover-server')
    const jpeg = await renderPdfPageOneToJpegBuffer(absPdf)
    await writeFile(absCover, jpeg)

    const coverImagePath = autoGeneratedCoverRelativePath(bookFolder)
    return {
      book: { ...book, coverImagePath },
      generated: true,
      linked: false,
    }
  } catch (error) {
    console.warn(`[book-cover-sync] Could not generate cover for book ${book.id}:`, error)
    return { book, generated: false, linked: false }
  }
}

export async function libraryNeedsCoverSync(payload: BookLibraryPayload): Promise<boolean> {
  const libraryRoot = getBookLibraryRoot()
  const cwd = /* turbopackIgnore: true */ process.cwd()
  for (const book of payload.books) {
    const existing = await resolveExistingCoverPath(book, libraryRoot, cwd)
    if (!existing) {
      if (resolvePrimaryUnitPdfPath(book)) return true
    } else if (book.coverImagePath?.trim() !== existing) {
      return true
    }
  }
  return false
}

/**
 * Ensures every book has a persisted cover image on disk and `coverImagePath` in the manifest.
 * Skips books that already have a valid cover file (including teacher-uploaded images).
 */
export async function ensureMissingBookCovers(
  payload: BookLibraryPayload,
): Promise<BookCoverSyncResult> {
  const libraryRoot = getBookLibraryRoot()
  const cwd = /* turbopackIgnore: true */ process.cwd()
  const updatedBookIds: string[] = []
  let generatedCount = 0
  let linkedCount = 0

  const books: BookRecord[] = []
  for (const book of payload.books) {
    const result = await ensureBookCover(book, libraryRoot, cwd)
    books.push(result.book)
    if (result.book.coverImagePath !== book.coverImagePath) {
      updatedBookIds.push(book.id)
    }
    if (result.generated) generatedCount += 1
    if (result.linked) linkedCount += 1
  }

  return {
    payload: { books },
    updatedBookIds,
    generatedCount,
    linkedCount,
  }
}

/** Sync missing covers and persist manifest when anything changed. */
export async function syncMissingBookCoversAndPersist(
  payload: BookLibraryPayload,
): Promise<BookLibraryPayload> {
  const needsSync = await libraryNeedsCoverSync(payload)
  if (!needsSync) return payload

  const result = await ensureMissingBookCovers(payload)
  if (result.updatedBookIds.length === 0) return payload

  await saveBookLibraryManifest(result.payload)
  return result.payload
}
