import type { BookRecord } from '@/lib/books/types'

/** Default auto-generated cover filename (matches manual upload convention). */
export const AUTO_GENERATED_COVER_FILE_NAME = 'cover.jpg'

export function resolveBookFolderFromUnitPath(filePath: string): string | null {
  const normalized = filePath.replaceAll('\\', '/')
  const match = normalized.match(/^book-library\/([^/]+)\//)
  return match?.[1] ?? null
}

export function autoGeneratedCoverRelativePath(bookFolder: string): string {
  return `book-library/${bookFolder}/${AUTO_GENERATED_COVER_FILE_NAME}`.replaceAll('\\', '/')
}

export function resolvePrimaryUnitPdfPath(book: BookRecord): string | null {
  const unitPath = book.units[0]?.filePath?.trim()
  return unitPath || null
}

export function resolveBookFolderForBook(book: BookRecord): string | null {
  for (const unit of book.units) {
    const folder = resolveBookFolderFromUnitPath(unit.filePath)
    if (folder) return folder
  }
  return null
}
